### ISSUE TITLE
Can't run some things twice in the same notebook instance

### ISSUE THREAD

**Issue by pc494** [pc494/pyxem#8]
```
indexer = IndexationGenerator(dp, library)
match_results = indexer.correlate(n_largest=1)
```

**Comment by pc494** [comment]
```
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/pc494/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 890, in __del__
    self.close()
  File "/home/pc494/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm_notebook.py", line 210, in close
    super(tqdm_notebook, self).close(*args, **kwargs)
  File "/home/pc494/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1118, in close
    if self.disable:
AttributeError: 'tqdm_notebook' object has no attribute 'disable'
```

May be somewhere to start?

**Comment by pc494** [comment]
Yeah tqdm is the problem, no solution as of yet.

**Comment by pc494** [comment]
This is a duplicated of #2
